// Automatically generated by astro-icon
// 73d1390eda7576637f52ce8e40d78169db4cfed80b1b50d319016d3b97e3e5ce

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "afcChampionLogo"
		| "American_Football_Conference_logo"
		| "helmet"
		| "loading";
}