// Automatically generated by astro-icon
// ed5c23d5f6409e0037a0e57b9642094ea6c50df2eae151e9ceb0951d710e663b

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "afcChampionLogo"
		| "helmet"
		| "loading"
		| "nfcChampionLogo";
}